### ISSUE TITLE
图片丢失反馈

### ISSUE THREAD

**Issue by dagufei** [TechMiZ/ToonShadingCollection#1]
打开——
03_DirectDiffuse漫反射篇.md

搜索——
 综合配色设计实践案例参考

可以看到插图（CH03_directDiffuse_F_ColorDesignExample1——7）全部丢失

**Comment by TechMiZ** [comment]
抱歉才看到，是路径的斜杠反了，最新提交已修复，谢谢提醒！

**Comment by dagufei** [comment]
&nbsp;


勇猛的轮子
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mi ***@***.***&gt;; 
发送时间: 2022年10月12日(星期三) 下午2:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TechMiZ/ToonShadingCollection] 图片丢失反馈 (Issue #1)





 
抱歉才看到，是路径的斜杠反了，最新更新已修复，谢谢提醒！
